# Generated by Django 5.0.14 on 2026-03-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='location',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Lokalizacja (Hala/Linia)'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='priority',
            field=models.CharField(choices=[('L', 'Niski'), ('M', 'Średni'), ('H', 'Wysoki'), ('C', 'Krytyczny')], default='M', max_length=1, verbose_name='Priorytet'),
        ),
    ]
