# Generated by Django 5.0.14 on 2026-03-31 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0003_maintenaceschedule"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MaintenaceSchedule",
            new_name="MaintenanceSchedule",
        ),
    ]
