# Generated by Django 5.0.14 on 2026-03-21 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa kategorii')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa części')),
                ('type_model', models.CharField(blank=True, max_length=100, verbose_name='Typ/Model')),
                ('unique_code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Unikalny kod (SKU)')),
                ('barecode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/', verbose_name='Kod kreskowy/QR')),
                ('quantity', models.IntegerField(default=0, verbose_name='Ilość na stanie')),
                ('min_quantity', models.IntegerField(default=1, verbose_name='Stab minimalny (Alert)')),
                ('location', models.CharField(blank=True, max_length=500, verbose_name='Lokalizacja (Regał/Półka)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena naetto (PLN)')),
                ('supplier_link', models.URLField(blank=True, max_length=500, verbose_name='Link do dostawcy/dokumantacji')),
                ('image', models.ImageField(blank=True, null=True, upload_to='part_images/', verbose_name='Zdjęcie poglądowe')),
                ('assigment', models.CharField(blank=True, max_length=500, verbose_name='Przeznaczenie/Opis')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='warehouse.category', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Część magazynowa',
                'verbose_name_plural': 'Części magazynowe',
            },
        ),
    ]
