# Generated by Django 5.0.14 on 2026-03-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='min_quantity',
            field=models.IntegerField(default=1, verbose_name='Stan minimalny (Alert)'),
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena netto (PLN)'),
        ),
        migrations.AlterField(
            model_name='part',
            name='supplier_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link do dostawcy/dokumentacji'),
        ),
    ]
