# Generated by Django 5.0.14 on 2026-03-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_machine_location_alter_workorder_priority'),
        ('warehouse', '0002_alter_part_min_quantity_alter_part_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='assigment',
        ),
        migrations.AddField(
            model_name='part',
            name='machines',
            field=models.ManyToManyField(blank=True, related_name='compatible_parts', to='maintenance.machine', verbose_name='Pasuje do maszyn'),
        ),
    ]
